package lt.vaidotas.bes.generator;

import java.math.BigInteger;

import lt.vaidotas.bes.generatable.BigInteger8BitGeneratable;
/**
 * 
 * @author Vaidotas
 * Generator for generating big integers, where each next value is 
 * generated by multiplying previous value by constant (multiplier),
 * and taking remainder of division
 * by other constant (divisor). Numbers are compared on last 8 bits. 
 */
public class MultiplicativeRemainderGenerator extends SequentialGenerator<BigInteger8BitGeneratable> {
    
    private final BigInteger divisor;
    private final BigInteger multiplier;
    private final BigInteger seed;
    
    public MultiplicativeRemainderGenerator(BigInteger pDivisor, 
            BigInteger pMultiplier, BigInteger pSeed){
        this.divisor = pDivisor;
        this.multiplier = pMultiplier;
        this.seed = pSeed;
        initialize();
    }

    @Override
    public BigInteger8BitGeneratable generateNextFromCurrent(
            BigInteger8BitGeneratable current) {
        return  multiplyAndTakeRemainder(current.getObjectHolder());
    }
    
    protected void initialize(){
        this.currentElement = multiplyAndTakeRemainder(seed);
    }
    
    private BigInteger8BitGeneratable multiplyAndTakeRemainder(BigInteger number){
        return new BigInteger8BitGeneratable(number.multiply(multiplier).remainder(divisor));
    }
}
